# Site settings
title: Shreyas V. Srinivasan
description: Personal website for Shreyas V. Srinivasan
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://shreyas.finance" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shreyas V. Srinivasan
user_description: My name is Shreyas and I am a junior at MIT studying math and computer science. I'll be completing my undergrad this spring, with plans to pursue a Master of Finance at MIT Sloan starting in the fall. My career interests are in quantitative finance and trading, and I'm also interested in academic finance research.
user_title: Math + CS @ MIT
email: shreyass@mit.edu
github_username: shreysrins

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
