# Site settings
title: Shreyas V. Srinivasan
description: Personal website for Shreyas V. Srinivasan
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://shreyas.finance" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shreyas V. Srinivasan
user_description: My name is Shreyas and I am a Master of Finance candidate at MIT Sloan. I previously completed my undergrad in math and computer science at MIT. My career interests are in quantitative trading, with internship experiences in fixed income options, equity derivatives, and equities stat arb. I'm also interested in academic finance research. In my free time, I enjoy DJing, poker, basketball, and day trading.
user_title: MFin @ MIT Sloan
email: shreyass@sloan.mit.edu
github_username: shreysrins

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
