# Site settings
title: Shreyas V. Srinivasan
description: Personal website for Shreyas V. Srinivasan
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://shreyas.finance" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shreyas V. Srinivasan
user_description: Shreyas is an undergraduate student at MIT interested in quantitative finance, derivatives trading, and data science. He's also an incoming Master of Finance candidate at MIT Sloan.
user_title: MIT '22, MFin '22
email: shreyass@mit.edu
# twitter_username: lorem_ipsum
github_username: shreysrins
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
